NVIDIA/NeMo-Framework-Launcher

csp_tools/aws/Dockerfile

Hi @maanug-nv, @yaoyu-33, @markelsanz14,
this PR fixes csp_tools/aws/Dockerfile. Without the PR, it would fail as
```
Step 4/11 : RUN apt-get update &&     cd /tmp &&     curl -O https://efa-installer.amazonaws.com/aws-efa-installer-${EFA_INSTALLER_VERSION}.tar.gz  &&     tar -xf aws-efa-installer-${EFA_INSTALLER_VERSION}.tar.gz &&     cd aws-efa-installer/DEBS/UBUNTU2004/$(uname -m) &&     dpkg -i libfabric*.deb &&     dpkg -i efa-profile*.deb &&     ldconfig &&     rm -rf /tmp/aws-efa-installer /var/lib/apt/lists/* &&     /opt/amazon/efa/bin/fi_info --version
---> Running in 2f8c389b9bc9
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security/main …
```

Fix aws efa installation

---

README.md

The path for the AWS Dockerfile is incorrect. This PR fixes it.

Fix incorrect AWS Dockerfile path

---

README.md

This fixes the incorrect path to the `nemo-data-curator` for the container copy command (provided in section 5.1.1.1) that was introduced in #33 .

Fix the incorrect path for the nemo-data-curator within the container

---

README.md
launcher_scripts/conf/config.yaml
launcher_scripts/conf/evaluation/gpt3/evaluate_all.yaml
launcher_scripts/conf/evaluation/gpt3/evaluate_lambada.yaml
launcher_scripts/nemo_launcher/collections/eval_harness/lm_eval/models/nemo_gpt3.py
launcher_scripts/nemo_launcher/core/stages.py

When training GPT with interleaved pipeline parallelism, the model bust be converted to a non-interleaved model. The conversion script creates a .nemo file so the GPT eval suite must be updated to use a .nemo file.

Add nemo model support for gpt eval

---

launcher_scripts/nemo_launcher/core/stages.py

This is to support UB-AllGather overlap for 5b, 20b, 40b. This gives 4-5% speedup.

Skip UB-AllGather overlap only when (1) BF16 and (2) PP>1

---

Dockerfile
README.md
launcher_scripts/conf/cluster/k8s.yaml
launcher_scripts/conf/config.yaml
launcher_scripts/conf/data_preparation/gpt3/download_gpt3_pile.yaml
launcher_scripts/nemo_launcher/collections/dataprep_scripts/pile_dataprep/download.py
launcher_scripts/nemo_launcher/collections/dataprep_scripts/pile_dataprep/extract.py
launcher_scripts/nemo_launcher/collections/dataprep_scripts/pile_dataprep/preprocess.py
launcher_scripts/nemo_launcher/core/data_stages.py
launcher_scripts/nemo_launcher/core/export_stages.py
launcher_scripts/nemo_launcher/core/k8s_templates/conversion/Chart.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/conversion/conversion.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/conversion/values.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/data_preparation/Chart.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/data_preparation/data-prep-config.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/data_preparation/data-prep.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/data_preparation/values.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/evaluation/Chart.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/evaluation/evaluation-config.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/evaluation/evaluation.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/evaluation/values.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/training/Chart.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/training/training-config.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/training/training.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/training/values.yaml
launcher_scripts/nemo_launcher/core/launchers.py
launcher_scripts/nemo_launcher/core/stages.py

Adding kubernetes support for preparing datasets and training GPT-based foundation models with NeMo Framework. The kubernetes support creates a Helm chart based off the cluster config settings and each task is launched as a distributed job via Helm. Currently, kubernetes support assumes the following:
* Recent versions of the GPU, Network, and Kubeflow Operators are installed.
* InfiniBand adapters are labeled as node resources if running multi-node jobs.
* The launcher is run from a controller node with access to `kubectl` and `helm` and can launch jobs on the cluster.
* The controller node has the ability to install various Python dependencies, including Hydra.
* All data including the launcher scripts and results/checkpoints will be stored on an NFS filer attached to all nodes.
A new …

Add support for training GPT models on Kubernetes

---

launcher_scripts/conf/training/gpt3/1b_improved.yaml
launcher_scripts/conf/training/gpt3/400m_improved.yaml
launcher_scripts/conf/training/gpt3/40b_improved.yaml
launcher_scripts/conf/training/gpt3/7b_improved.yaml

Signed-off-by: dimapihtar <dpihtar@gmail.com>

---

launcher_scripts/nemo_launcher/core/data_stages.py

I think I found a bug in custom dataset.
When a full path to a directory (i.e. /data/nemo/custom_dataset/c4) is passed which contains .gz files (i.e. i manually downloaded c4 en) this [line](https://github.com/NVIDIA/NeMo-Megatron-Launcher/blob/a5afbe3b8060ceec53c7afaa9138ec8b0b7aa023/launcher_scripts/nemo_launcher/core/data_stages.py#L544C28-L544C28) overrides raw_dataset_files and then fails to call os.stat(x) on line 546.
Steps
1. Download c4 en
2. Set launcher_scripts/conf/data_preparation/generic/custom_dataset.yaml key as below
```
raw_dataset_files: /data/nemo/custom_dataset/c4/en
```
3. Run data perperation step with custom dataset
Error:
```
Traceback (most recent call last):
File "/home/zlapp/nvai4/launcher_scripts/main.py", line 82, in main
job_id = stage.run()
File …
```

Bugfix raw_dataset_files with custom data

---

launcher_scripts/conf/config.yaml
launcher_scripts/nemo_launcher/core/stages.py
launcher_scripts/tests/unit_tests/config_tests/test_main_config.py

On BCP clusters the W&B token can be specified as a cluster secret that is exposed in the job as an environment variable. Reading the key directly from the EV minimizes steps to get started with W&B on BCP.

Accept W&B token directly from BCP secret

---

launcher_scripts/nemo_launcher/collections/eval_harness/download.py

This is to fix a issue when run evaluation stage on DGX cloud, 
```
python3 /opt/NeMo-Megatron-Launcher/launcher_scripts/main.py \
data_dir=/mount_workspace/data  stages=[evaluation] cluster_type=bcp \
...
```
the above script would generate bcprun command like this 
```
bcprun --nnodes 1 --npernode 1 -no_redirect  --env 'TRANSFORMERS_OFFLINE=1' --env 'TORCH_NCCL_AVOID_RECORD_STREAMS=1' --env 'NCCL_NVLS_ENABLE=0' --cmd "
python3 /opt/NeMo-Megatron-Launcher/launcher_scripts/nemo_launcher/collections/eval_harness/download.py \
--tasks=all_tasks \
--cache-dir=/mount_workspace/data/eval_harness_data"
```
but the eval datasets are not download to the `cache-dir`, because the download.py instead expected **_underscore_** version of `cache_dir`.

fix eval_harness download cache-dir

---

launcher_scripts/conf/data_preparation/generic/custom_dataset.yaml
launcher_scripts/nemo_launcher/collections/dataprep_scripts/custom_dataprep/preprocess.py
launcher_scripts/nemo_launcher/collections/dataprep_scripts/mc4_dataprep/preprocess.py
launcher_scripts/nemo_launcher/collections/dataprep_scripts/pile_dataprep/preprocess.py
launcher_scripts/nemo_launcher/core/data_stages.py

This update allows the custom dataset preprocessor to handle different types of tokenizers including BPE with GPT2Tokenizer and `sentencepiece`. Users can either train a `sentencepiece` tokenizer alongside the data prep or download an existing tokenizer.
This additionally updates the BCP custom data prep to run as much as 20x faster by launching `bcprun` without `mpirun` to maximize the CPU core usage on all nodes.

Support additional tokenizers for custom datasets

---

launcher_scripts/conf/data_curation/common_crawl/curate_common_crawl.yaml
launcher_scripts/conf/data_curation/common_crawl/fasttext_download/fasttext_download.yaml
launcher_scripts/nemo_launcher/collections/datacuration_scripts/download_fasttext.sh
launcher_scripts/nemo_launcher/core/data_curation_stages.py

The choose language stage modifies the pipeline memory but does not actually launch a SLURM job and therefore does not return a `job_id`. This breaks the dependency chain, causing the next job to be run as a singleton instead of depending on the job prior to the choose language stage like it should.
This change keeps the dependency chain that by taking the previous `job_id` and returning that in the run stage. It has been tested by running the `common_crawl/curate_common_crawl` data curation on a small dataset and inspecting the bash scripts that were produced as well. It will also now throw an error if not properly used to ensure the user is able to debug quickly.
Another smaller change has been made to remove a placeholder that the user was not meant to modify. The `<Path to the FasText …

Fix dependency being overwritten with special stage

---

launcher_scripts/conf/config.yaml
launcher_scripts/tests/unit_tests/config_tests/test_main_config.py

1. Disable FP8 AMAX reduction in data-parallel domain
2. Enable async FP8 AMAX reduction (overlap with the following computes)

Set FP8 AMAX reduction env vars for perf improvement

---

launcher_scripts/nemo_launcher/core/launchers.py

This should allow dry-runs without risk of re-submitting

Have the k8s launcher respect NEMO_LAUNCHER_DEBUG and print the template instead of installing it

---

launcher_scripts/conf/training/gpt3/175b.yaml
launcher_scripts/conf/training/gpt3/175b_fp8.yaml
launcher_scripts/conf/training/gpt3/20b.yaml
launcher_scripts/conf/training/gpt3/40b.yaml
launcher_scripts/conf/training/gpt3/5b.yaml
launcher_scripts/conf/training/llama/llama2_13b.yaml
launcher_scripts/conf/training/llama/llama2_70b.yaml
launcher_scripts/conf/training/llama/llama2_7b.yaml
launcher_scripts/conf/training/tp_overlap/ub_cfg_a100_h12288_tp4_mbs1_seqlen2048.yaml
launcher_scripts/conf/training/tp_overlap/ub_cfg_a100_h12288_tp4_mbs2_seqlen2048.yaml
launcher_scripts/conf/training/tp_overlap/ub_cfg_h100_h12288_tp4_mbs1_seqlen2048.yaml
launcher_scripts/conf/training/tp_overlap/ub_cfg_h100_h12288_tp8_mbs2_seqlen2048.yaml
launcher_scripts/nemo_launcher/core/stages.py

Previously, we were supposed to give dummy config files as Hydra expected some file for the config. We now set the default for this file for all the GPT/LLAMA configs to be optional and will be taken based on the command line if the user wants to tune the config.
If a user wants to add a config, they can add this line below to their Launcher run script:
training/tp_overlap@training.model.ub_tp_comm_overlap_cfg=ub_cfg_h100_h5120_tp2_mbs1_seqlen4096
They should have a YAML file of name ub_cfg_h100_h5120_tp2_mbs1_seqlen4096.yaml in their tp_overlap/ directory adjacent to the LLAMA/GPT conf directory. If they don't add this line, default configs are used.

Added optional TP overlap config file addition

---

launcher_scripts/conf/cluster/k8s.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/training/training.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/training/values.yaml
launcher_scripts/nemo_launcher/core/stages.py

This PR adds the ability to specify multiple IB resources in the pytorchjob by plumbing annotations from `k8s.yaml`. This also adds the missing annotation required to request IB resources for the training stage. It remains backward compatible to allow specifying a single resource without the list notation. Below are example invocations:
- multiple
```
python3 launcher_scripts/main.py \
cluster=k8s cluster_type=k8s \
'cluster.ib_resource_name=[nvidia.com/resibp12s0,nvidia.com/resibp186s0]' \
'cluster.ib_count=[1,1]' cluster.ib_network_annotation=\'ibp12s0,ibp186s0\'
```
- single
```
python3 launcher_scripts/main.py \
cluster=k8s cluster_type=k8s \
cluster.ib_resource_name=nvidia.com/hostdev \
cluster.ib_count=8
```
In a follow up PR, I need to plumb this to all stages with k8s support.

Added feature to specify multiple IB resources for trianing k8s template.

---

examples/peft/llama/a100/lora_4gpu_k8s.sh
launcher_scripts/conf/cluster/k8s.yaml
launcher_scripts/conf/config.yaml
launcher_scripts/conf/peft/gpt3/squad.yaml
launcher_scripts/conf/peft/llama/squad.yaml
launcher_scripts/conf/peft/t5/squad.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/peft/Chart.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/peft/peft-config.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/peft/peft.yaml
launcher_scripts/nemo_launcher/core/k8s_templates/peft/values.yaml
launcher_scripts/nemo_launcher/core/launchers.py
launcher_scripts/nemo_launcher/core/stages.py

Replaces #202 
-------------------
This work builds upon #138 .
This adds the PEFT k8s stage with configs for gpt3/llama/t5 models and provides some documentation and example scripts.
These PEFT configs have been validated for LoRa on the above models.
* This is the first k8s stage to also use the release name in all the resources created on the cluster. This now makes it possible for someone to submit multiple submissions in parallel. Previously, the would have collided either on disk (local results_dir) or b/c the helm chart deployed a pytorchjob/configmap that had a static name (not dependent on the release name)
* This also introduces a `volumes` key in `k8s.yaml` to specify hostPath, NFS, or PVCs and is backward compatible with the previous support, which only allowed NFS.
* PEFT …

Adds K8s PEFT(LoRa) support to the launcher

---

launcher_scripts/nemo_launcher/core/launchers.py

On Base Command Platform, the Log tab will display the launched job's STDOUT in addition to the results being piped to a log file.

Output STDOUT to Log tab on BCP

---

launcher_scripts/conf/training/gpt3/126m.yaml
launcher_scripts/conf/training/gpt3/175b.yaml
launcher_scripts/conf/training/gpt3/175b_fp8.yaml
launcher_scripts/conf/training/gpt3/1b_improved.yaml
launcher_scripts/conf/training/gpt3/20b.yaml
launcher_scripts/conf/training/gpt3/400m_improved.yaml
launcher_scripts/conf/training/gpt3/40b.yaml
launcher_scripts/conf/training/gpt3/40b_improved.yaml
launcher_scripts/conf/training/gpt3/5b.yaml
launcher_scripts/conf/training/gpt3/7b_improved.yaml

Disable the use of atomic-counter GEMM in tensor-parallel communication.
The performance of atomic-GEMM is still under exploration.

Disable the use of atomic-counter GEMM in tensor-parallel communication

---

launcher_scripts/nemo_launcher/core/stages.py

Fixes bug introduced by #214. NFSPath/NFSServer were removed too early since they were still depended on by stage helm charts.

Restore NFSPath/NFSServer in k8s launcher

---

launcher_scripts/conf/steerlm_reg/ac_sft/gpt_sft.yaml

Per slack channel discussion, link [here ](https://nvidia.slack.com/archives/C05L3FR8Z9C/p1713464161235309), a customer raise question of gpt_sft.yaml which , according to Zhilin , this yaml needs to be updated to the NeMo-Aligner's train_ds yaml configuration. 
I have updated the configuration of the train_ds section in the NeMo Megatron Launcher / launcher_scripts/conf/steerlm_reg/ac_sft/gpt_sft.yaml file 
Please merge this PR to the main. Thank you

fixing train_ds as per comment from Zhilin on slack

---

.pre-commit-config.yaml
launcher_scripts/nemo_launcher/core/v2/config_k8s.py
launcher_scripts/nemo_launcher/core/v2/stages.py
launcher_scripts/nemo_launcher/core/v2/step_k8s.py
launcher_scripts/nemo_launcher/utils/file_utils.py

Using `|` (e.g. `str | None`) is only supported in Python 3.10. To support machines/clusters with Python 3.9 or older, this PR converts those typehints to `typing.Union` or `typing.Optional`.

Support Python 3.9 typehinting syntax

---

launcher_scripts/conf/training/mixtral/mixtral_8x7b.yaml

Revert enabling mcore-dist-opt in mixtral config; Will re-enable once mcore-dist-opt support has been finalized.

remove mcore-dist-opt (for now)

---

launcher_scripts/conf/config.yaml
launcher_scripts/nemo_launcher/collections/dataprep_scripts/pile_dataprep/preprocess.py
launcher_scripts/tests/unit_tests/config_tests/test_main_config.py

Prefer the user specified TRANSFORMERS_CACHE if available, otherwise fallback to default.
the issues were two
1. it was hardcoding the transformers_cache env var and so if you specify it in the outer script it would not pass it down.
2. the tokenizer-library was always being megatron & not changing if the use used HF

use env TRANSFORMERS_CACHE if available

---

launcher_scripts/conf/peft/llama/sft.yaml
launcher_scripts/conf/peft/nemotron/sft.yaml

- Set transformer_engine=true explicitly in both configs, due to the recent change in function of this flag (which could cause `AssertionError: (RMSNorm) is not supported in FusedLayerNorm when instantiating FusedLayerNorm` if it was unset)
- Set answer_only_loss=true by default for nemotron, which improves convergence

Small updates for llama2 and nemotron base configs

---

launcher_scripts/conf/rag_generating/gpt3/125m.yaml
launcher_scripts/conf/rag_generating/gpt3/7b.yaml
launcher_scripts/conf/rag_indexing/bert/110m.yaml
launcher_scripts/conf/rag_indexing/bert/340m.yaml
launcher_scripts/nemo_launcher/core/stages.py

The main changes are adding optional package install command "pip install llama-index==0.10.33" into method `make_stage_command_groups ` of class `RAGIndexing` and `RAGGenerating`, by overriding that method from the parent class `NeMoStage`.

Updates to RAG pipeline stages to install optional dependencies packages

---

launcher_scripts/conf/conversion/mistral/convert_mistral.yaml
launcher_scripts/conf/evaluation/mixtral/evaluate_all.yaml
launcher_scripts/conf/evaluation/mixtral/evaluate_all_8x22b.yaml
launcher_scripts/conf/evaluation/peft_mixtral/squad.yaml
launcher_scripts/conf/evaluation/peft_mixtral/squad_8x22b.yaml
launcher_scripts/conf/fine_tuning/mistral/squad.yaml
launcher_scripts/conf/fine_tuning/mixtral/squad.yaml
launcher_scripts/conf/fine_tuning/mixtral/squad_8x22b.yaml
launcher_scripts/conf/peft/mixtral/squad.yaml
launcher_scripts/conf/training/mixtral/mixtral_8x7b.yaml

Avoid triggering `raise ValueError(
ValueError: When using expert parallelism and tensor parallelism, sequence parallelism must be used`, since both EP & TP are enabled.

enable SP in mixtral-8x7b

---

launcher_scripts/nemo_launcher/core/v2/stages.py

Some k8s platforms can overwrite LD_LIBRARY_PATH variables which can prevent the container from recognizing CUDA drivers in some scenarios. Adding the LD_LIBRARY_PATH EV to mpirun commands ensures that the spawned processes with mpirun will be able to see the necessary libraries. The LD_LIBRARY_PATH EV can also be set while launching jobs.

Pass LD_LIBRARY_PATH EV to mpirun command

---

launcher_scripts/conf/training/llama/llama3_1_405b.yaml
launcher_scripts/conf/training/llama/llama3_1_70b.yaml
launcher_scripts/conf/training/llama/llama3_1_8b.yaml
launcher_scripts/conf/training/llama/llama3_70b.yaml
launcher_scripts/conf/training/llama/llama3_8b.yaml

According to [Llama 3 blog post](https://ai.meta.com/blog/meta-llama-3/), "We trained the models on sequences of 8,192 tokens, using a mask to ensure self-attention does not cross document boundaries.". The current Llama 3 configs don't use attention masking for self-attention.

Enabled attention masking for Llama 3 according to the model card

---

launcher_scripts/nemo_launcher/collections/hparams_override.py

Avoid raising TimeoutError on node-1 if node-0 hasn't started yet.

timeout only on first node

---

launcher_scripts/nemo_launcher/collections/hparams_override.py

For debugging purposes (e.g. missing mounts)

add path access checking

---

launcher_scripts/nemo_launcher/core/stages.py

Profiling with Nsight systems is enabled but additional option of GPU metrics is optional in some systems that can add valuable trace info. 
The addition enables that ability for the profiled rank attached GPU in privileged systems and is disabled by default.

Add GPU metrics support for nsight profiling
