NVIDIA/NeMo-Framework-Launcher

- .pre-commit-config.yaml
- auto_configurator/autoconfig/scripts/compare_throughput.py
- launcher_scripts/main.py
- launcher_scripts/nemo_launcher/collections/dataprep_scripts/pile_dataprep/preprocess.py
- launcher_scripts/nemo_launcher/collections/eval_harness/evaluate.py
- launcher_scripts/nemo_launcher/collections/eval_harness/lm_eval/tasks/prompt.py
- launcher_scripts/nemo_launcher/collections/eval_harness/lm_eval/tasks/race.py
- launcher_scripts/nemo_launcher/collections/eval_harness/lm_eval/tasks/superglue.py
- launcher_scripts/nemo_launcher/collections/eval_harness/lm_eval/tasks/winogrande.py
- launcher_scripts/nemo_launcher/collections/export_scripts/prepare_triton_model_config.py
- launcher_scripts/nemo_launcher/core/data_stages.py
- launcher_scripts/nemo_launcher/core/stages.py
- setup.cfg
This PR adds pre-commit-config, and then reformat the code. I believe the code style should be aligned with [NeMo](https://github.com/NVIDIA/NeMo) now.
You could use `pre-commit run -a` to automatically check and reformat the python code.
Please let me know if README should be updated too. Thanks.
> Add pre-commit-config and reformat the code

- launcher_scripts/nemo_launcher/collections/dataprep_scripts/dolly_dataprep/__init__.py
- launcher_scripts/nemo_launcher/collections/dataprep_scripts/dolly_dataprep/download.py
- launcher_scripts/nemo_launcher/collections/dataprep_scripts/dolly_dataprep/preprocess.py
1) Added downloading script.
2) Added preprocessing script with two options of preprocessed dataset type ('mmap' and 'text').
> add dolly data preprocess scripts

- README.md
This PR adds section 5.16 to the launcher README, which discusses the NeMo Data Curator. Additionally, I have added the directory /opt/NeMo-Data-Curator as an additional directory to the list of directories to be copied out of the container.
> Add section for Nemo data curator

- README.md
Update readme for dialogue SFT
> Update readme for dialogue SFT

- launcher_scripts/conf/training/gpt3/126m.yaml
- launcher_scripts/conf/training/gpt3/175b.yaml
- launcher_scripts/conf/training/gpt3/1b_improved.yaml
- launcher_scripts/conf/training/gpt3/20b.yaml
- launcher_scripts/conf/training/gpt3/400m_improved.yaml
- launcher_scripts/conf/training/gpt3/40b.yaml
- launcher_scripts/conf/training/gpt3/40b_improved.yaml
- launcher_scripts/conf/training/gpt3/5b.yaml
- launcher_scripts/conf/training/gpt3/7b_improved.yaml
Add improvements to training config for GPT functional tests
> Interleaved add improvements to config

- launcher_scripts/conf/training/gpt3/1b_improved.yaml
- launcher_scripts/conf/training/gpt3/400m_improved.yaml
- launcher_scripts/conf/training/gpt3/40b_improved.yaml
- launcher_scripts/conf/training/gpt3/7b_improved.yaml
> 40Bimp config changes

- launcher_scripts/conf/training/gpt3/126m.yaml
> Turn of TE for 126m

- README.md
- launcher_scripts/conf/training/gpt3/126m.yaml
- launcher_scripts/conf/training/gpt3/175b.yaml
- launcher_scripts/conf/training/gpt3/1b_improved.yaml
- launcher_scripts/conf/training/gpt3/20b.yaml
- launcher_scripts/conf/training/gpt3/400m_improved.yaml
- launcher_scripts/conf/training/gpt3/40b.yaml
- launcher_scripts/conf/training/gpt3/40b_improved.yaml
- launcher_scripts/conf/training/gpt3/5b.yaml
- launcher_scripts/conf/training/gpt3/7b_improved.yaml
- Set the fp8-associated knobs for easy running of fp8 jobs
- Update README
> GPT pre-train script update for fp8 training

- launcher_scripts/conf/training/gpt3/126m.yaml
- launcher_scripts/conf/training/gpt3/1b_improved.yaml
- launcher_scripts/conf/training/gpt3/20b.yaml
- launcher_scripts/conf/training/gpt3/400m_improved.yaml
- launcher_scripts/conf/training/gpt3/40b.yaml
- launcher_scripts/conf/training/gpt3/40b_improved.yaml
- launcher_scripts/conf/training/gpt3/5b.yaml
- launcher_scripts/conf/training/gpt3/7b_improved.yaml
- launcher_scripts/nemo_launcher/core/stages.py
- Set gc_interval as min (gc_interval, validation interval)
- Set gc_interval to zero for the model w/o PP (removing gc_interval)
> gc_interval fix for the case validation interval is shorter than gc_interval

- examples/training/gpt/README.md
Added instructions to run with synthetic data on an interactive node.
> Update README.md with instructions to run with synthetic data on an interactive node

- launcher_scripts/conf/config.yaml
- launcher_scripts/conf/quality_filtering/heuristic/english.yaml
- launcher_scripts/main.py
- launcher_scripts/nemo_launcher/core/data_curation_stages.py
- launcher_scripts/nemo_launcher/core/stages.py
This PR adds a new stage and configs to the launcher for quality filtering within the nemo data curator.
> Add NeMo Data Curator document quality filtering support in launcher

- README.md
> Update documentation of NeMo-RLHF

- README.md
`5.15.2 SFT Training` section update:
- described how to run SFT training on custom task with NeMo Megatron Launcher
> SFT training section update

- launcher_scripts/conf/training/gpt3/175b.yaml
- launcher_scripts/conf/training/gpt3/175b_fp8.yaml
- launcher_scripts/conf/training/gpt3/40b.yaml
(1) set ub_tp_overlap=False
(2) change 175b_performance.yaml to 175b_fp8.ymal
(3) use TP=4 and MBS=2 at 175b with FP8
> (1) set ub_tp_overlap=False, (2) change 175b_performance to 175b_fp8, (3) use TP=4 and MBS=2 at 175b with FP8

- launcher_scripts/conf/conversion/gpt3/convert_gpt3.yaml
- launcher_scripts/nemo_launcher/collections/checkpoint_search.py
Move `dist_ckpt` logic outside check for 'latest'.
> Debug #128

- launcher_scripts/nemo_launcher/core/k8s_templates/conversion/conversion.yaml
- launcher_scripts/nemo_launcher/core/k8s_templates/conversion/values.yaml
- launcher_scripts/nemo_launcher/core/k8s_templates/evaluation/evaluation.yaml
- launcher_scripts/nemo_launcher/core/k8s_templates/evaluation/values.yaml
- launcher_scripts/nemo_launcher/core/k8s_templates/training/training.yaml
- launcher_scripts/nemo_launcher/core/k8s_templates/training/values.yaml
- launcher_scripts/nemo_launcher/core/stages.py
The container environment variables are specified in the main config file. The kubernetes templates that are generated should use these user specified EVs instead of using hard-coded values.
> Set k8s environment variables based on config

- launcher_scripts/nemo_launcher/core/data_stages.py
The custom dataset preparation stage has been updated to process all custom files specified by the user. This fixes errors that were thrown during data preparation trying to reference variables that weren't yet assigned values.
> Fix custom dataset preparation

- auto_configurator/autoconfig/scripts/compare_throughput.py
- auto_configurator/autoconfig/training_config.py
- auto_configurator/base_configs/gpt3.yaml
AutoConfigurator fixes related to mcore changes
> autoconf fixes

- launcher_scripts/conf/rlhf_ppo/gpt3/2b_ppo.yaml
> fix config

- launcher_scripts/nemo_launcher/core/launchers.py
Need to propagate script results/return codes
> [Nemo] MAke ret_stdout in BCP same as slurm

- launcher_scripts/conf/config.yaml
- launcher_scripts/conf/lang_separation_and_cleaning/fasttext_download/fasttext_download.yaml
- launcher_scripts/conf/lang_separation_and_cleaning/lang_separation_and_cleaning.yaml
- launcher_scripts/conf/lang_separation_and_cleaning/language_identification/language_identification.yaml
- launcher_scripts/conf/lang_separation_and_cleaning/separate_by_language/separate_by_language.yaml
- launcher_scripts/conf/lang_separation_and_cleaning/text_cleaning/text_cleaning.yaml
- launcher_scripts/main.py
- launcher_scripts/nemo_launcher/collections/datacuration_scripts/download_fasttext.sh
- launcher_scripts/nemo_launcher/core/data_curation_stages.py
- launcher_scripts/tests/unit_tests/config_tests/test_main_config.py
Adds support for language separation and cleaning from the data curator.
> Add support for lang separation and cleaning

- launcher_scripts/conf/config.yaml
- launcher_scripts/conf/task_deduplication/find_matching_ngrams/find_matching_ngrams.yaml
- launcher_scripts/conf/task_deduplication/prepare_task_data/prepare_task_data.yaml
- launcher_scripts/conf/task_deduplication/remove_matching_ngrams/remove_matching_ngrams.yaml
- launcher_scripts/conf/task_deduplication/task_deduplication.yaml
- launcher_scripts/main.py
- launcher_scripts/nemo_launcher/core/data_curation_stages.py
- launcher_scripts/tests/unit_tests/config_tests/test_main_config.py
Adds support for decontamination of pretraining dataset with downstream tasks.
> Add task deduplication support

- launcher_scripts/conf/training/gpt3/126m.yaml
- launcher_scripts/conf/training/gpt3/175b.yaml
- launcher_scripts/conf/training/gpt3/175b_fp8.yaml
- launcher_scripts/conf/training/gpt3/1b_improved.yaml
- launcher_scripts/conf/training/gpt3/20b.yaml
- launcher_scripts/conf/training/gpt3/400m_improved.yaml
- launcher_scripts/conf/training/gpt3/40b.yaml
- launcher_scripts/conf/training/gpt3/40b_improved.yaml
- launcher_scripts/conf/training/gpt3/5b.yaml
- launcher_scripts/conf/training/gpt3/7b_improved.yaml
- launcher_scripts/nemo_launcher/core/stages.py
Add default context_parallel_size in GPT3 configs.
> add default context_parallel_size in GPT3 configs

- launcher_scripts/conf/data_preparation/steerlm/steerlm_data_prep1.yaml
> fixing typo in Step2-stage1 yaml

- launcher_scripts/conf/training/llama/llama2_13b.yaml
- launcher_scripts/conf/training/llama/llama2_70b.yaml
Added the paths for the hydra configs for LLAMA2 models.
> Added hydra conf paths for llama2 models

- Dockerfile
- requirements.txt
Packages used by launcher should exist in requirements file.
pytablewriter
https://github.com/NVIDIA/NeMo-Megatron-Launcher/blob/master/launcher_scripts/nemo_launcher/collections/eval_harness/evaluate.py#L483
best_download
https://github.com/NVIDIA/NeMo-Megatron-Launcher/blob/master/launcher_scripts/nemo_launcher/collections/eval_harness/lm_eval/tasks/lambada.py#L18
> Update Requirements File

- launcher_scripts/nemo_launcher/core/stages.py
- Fix error were squad dataset does not download for finetuning stage
> Fix Squad data prep for fintuning

- launcher_scripts/conf/peft/llama/sft.yaml
Adding TP comm overlap interface to the baseline SFT run script.
> Add tensor parallel communication overlap yaml config interface

- launcher_scripts/conf/training/nemotron/nemotron_15b.yaml
- launcher_scripts/conf/training/nemotron/nemotron_22b.yaml
- launcher_scripts/conf/training/nemotron/nemotron_8b.yaml
- launcher_scripts/nemo_launcher/core/stages.py
Added config files for Nemo Launcher, added support for using those files.
> Added nemotron models to Launcher

- launcher_scripts/conf/peft/llama/sft.yaml
- launcher_scripts/conf/peft/llama/squad.yaml
1. Set all the optimized configs as default (ignored in case not used)
> Improve LLAMA2 fining tuning config options

- launcher_scripts/conf/peft/code_llama/human_eval.yaml
Config for code llama peft on human_eval, following the config for `peft/llana/squad` and `fine_tuning/code_llama/human_eval`
> Add config for code llama peft

- launcher_scripts/conf/fine_tuning/mixtral/squad.yaml
- launcher_scripts/conf/peft/mixtral/squad.yaml
- launcher_scripts/conf/training/mistral/mistral_7b.yaml
- launcher_scripts/conf/training/mixtral/mixtral_8x7b.yaml
Updated the model section of training and finetuning config
> Mistral mixtral fix

- launcher_scripts/conf/evaluation/mixtral/evaluate_all.yaml
nemo-mixtral_8x7b not defined bu nemo-mixtral is
> Use nemo-mixtral instead of nemo-mixtral_8x7b

- launcher_scripts/conf/data_curation/common_crawl/curate_common_crawl.yaml
- launcher_scripts/conf/data_curation/common_crawl/fasttext_download/fasttext_download.yaml
- launcher_scripts/conf/data_curation/common_crawl/language_identification/language_identification.yaml
- launcher_scripts/conf/data_curation/common_crawl/prepare_task_data/prepare_task_data.yaml
- launcher_scripts/conf/data_curation/common_crawl/separate_by_language/separate_by_language.yaml
- launcher_scripts/conf/data_curation/common_crawl/text_cleaning/text_cleaning.yaml
- launcher_scripts/nemo_launcher/collections/run_dask_stage.sh
- launcher_scripts/nemo_launcher/core/data_curation_stages.py
Due to the recent refactor of the data curator, some of the launcher scripts and configs need to be updated. These changes have been tested on a small test dataset.
> Update Curator Scripts for Refactor

- launcher_scripts/nemo_launcher/core/stages.py
The paths of checkpoint converters needs to be updated due to https://github.com/NVIDIA/NeMo/pull/8435
> Fix converter path

- Dockerfile
Due to that
https://github.com/NVIDIA/NeMo/pull/8689/files#diff-7667eae242a8ef776bff78cd08e79bc81df4896a450f0a781f6ed317a3dfb7ffR38
Need newer version of pytorch lightning
> New pytorch lightning version

- launcher_scripts/conf/training/gpt3/175b.yaml
- launcher_scripts/conf/training/llama/llama2_70b.yaml
Made gc_interval switch to hard code to 10.
> Added gc_interval for manual garbage collection

- launcher_scripts/conf/data_curation/common_crawl/fasttext_download/fasttext_download.yaml
- launcher_scripts/conf/data_curation/common_crawl/prepare_task_data/prepare_task_data.yaml
- launcher_scripts/conf/data_curation/common_crawl/quality_filtering/heuristic_english.yaml
- launcher_scripts/conf/data_curation/sft/prepare_task_data/prepare_task_data.yaml
- launcher_scripts/nemo_launcher/collections/run_dask_stage.sh
- launcher_scripts/nemo_launcher/core/data_curation_stages.py
Adds the ability to control the number of Dask workers created in each stage of NeMo Curator. Also updates for the new module paths in the curator It has been tested on some sample datasets.
> Add more configuration options to NeMo Curator

- launcher_scripts/nemo_launcher/core/stages.py
Please help to review @yaoyu-33 , thanks
> fix bug for chatglm

- examples/training/llama/h100/llama3_70b_bf16.sh
- examples/training/llama/h100/llama3_70b_fp8.sh
- examples/training/llama/h100/llama3_8b_bf16.sh
- examples/training/llama/h100/llama3_8b_fp8.sh
- launcher_scripts/conf/training/llama/llama2_70b.yaml
- launcher_scripts/conf/training/llama/llama2_7b.yaml
- launcher_scripts/conf/training/llama/llama3_70b.yaml
- launcher_scripts/conf/training/llama/llama3_8b.yaml
- launcher_scripts/conf/training/tp_overlap/ub_cfg_h100_fp8_h8192_tp4_mbs1_seqlen8192.yaml
- launcher_scripts/conf/training/tp_overlap/ub_cfg_h100_h8192_tp4_mbs1_seqlen8192.yaml
- Add LLAMA3 8B and 70B configs
- Add userbuffer TP communication overlap config of 70B
- Enable `bias_dropout_add_fusion` for LLAMA2 configs
> Add llama3 8b and 70b configs

- README.md
- launcher_scripts/conf/config.yaml
- launcher_scripts/conf/ptq/llama2/quantization.yaml
- launcher_scripts/main.py
- launcher_scripts/nemo_launcher/core/stages.py
- launcher_scripts/tests/unit_tests/config_tests/test_main_config.py
- launcher_scripts/tests/unit_tests/stages_tests/test_ptq.py
Adding support for post-training quantization.
> PTQ stage in Launcher

- launcher_scripts/main.py
Adding mixtral/mistral to the data-prep stage dictionary.
> add mistral/mixtral to dataprep

- launcher_scripts/conf/training/mixtral/mixtral_8x3b.yaml
- launcher_scripts/conf/training/mixtral/mixtral_8x7b.yaml
Update to use distributed optimizer for mixtral 7B
> Use distributed optimizer for mixtral 7B

- launcher_scripts/nemo_launcher/core/data_curation_stages.py
One of the curator launcher stages was outdated and needed to be updated to properly use Dask. I have tested the stage and everything is working properly now.
> Fix bug in curator launcher stage

- launcher_scripts/conf/ptq/model/quantization.yaml
- launcher_scripts/nemo_launcher/core/stages.py
- launcher_scripts/tests/unit_tests/stages_tests/test_ptq.py
Related to change in https://github.com/NVIDIA/NeMo/pull/9276/
> Update PTQ config

- launcher_scripts/conf/ptq/model/quantization.yaml
- launcher_scripts/nemo_launcher/core/stages.py
Adding updates as a follow up for https://github.com/NVIDIA/NeMo/pull/9574 and https://github.com/NVIDIA/NeMo/pull/9326.
> PTQ updates

- launcher_scripts/conf/fine_tuning/mt5/custom_task.yaml
- launcher_scripts/conf/fine_tuning/mt5/xquad.yaml
- launcher_scripts/conf/fine_tuning/t5/custom_task.yaml
- launcher_scripts/conf/fine_tuning/t5/squad.yaml
- launcher_scripts/conf/peft/t5/squad.yaml
- launcher_scripts/conf/training/mt5/11b.yaml
- launcher_scripts/conf/training/mt5/170m.yaml
- launcher_scripts/conf/training/mt5/23b.yaml
- launcher_scripts/conf/training/mt5/390m.yaml
- launcher_scripts/conf/training/mt5/3b.yaml
- launcher_scripts/conf/training/t5/11b.yaml
- launcher_scripts/conf/training/t5/220m.yaml
- launcher_scripts/conf/training/t5/23b.yaml
- launcher_scripts/conf/training/t5/3b.yaml
- launcher_scripts/conf/training/t5/41b.yaml
Reverts NVIDIA/NeMo-Framework-Launcher#372
> Revert "update t5/mt5 configs"

- examples/training/llama/h100/llama3_405b_bf16.sh
- examples/training/llama/h100/llama3_405b_fp8.sh
- launcher_scripts/conf/training/llama/llama2_13b.yaml
- launcher_scripts/conf/training/llama/llama2_70b.yaml
- launcher_scripts/conf/training/llama/llama2_7b.yaml
- launcher_scripts/conf/training/llama/llama3_1_405b.yaml
- launcher_scripts/conf/training/llama/llama3_1_70b.yaml
- launcher_scripts/conf/training/llama/llama3_1_8b.yaml
- launcher_scripts/conf/training/llama/llama3_70b.yaml
- launcher_scripts/conf/training/llama/llama3_8b.yaml
- launcher_scripts/conf/training/tp_overlap/ub_cfg_h100_bf16_h16384_tp8_cp2_mbs1_seqlen8192.yaml
- launcher_scripts/conf/training/tp_overlap/ub_cfg_h100_fp8_h16384_tp8_cp2_mbs1_seqlen8192.yaml
- Update LLAMA2, 3 configs
- Add new TP comm overlap configs for LLAMA3.1
> update llama2/3 configs
